[tool.poetry]
name = "gjango-homework-1"
version = "0.1.0"
description = ""
authors = ["Polyaaaaaa <polinasatrajkina@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
gh = "^0.0.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
